name: Publish on Docker Hub and Deploy

on:
  push:
    branches: [ dev ] # Change to master on production
  pull_request:
    branches: [ dev ] # Change to master on production

jobs:
  build_and_pub:
    name: Push Docker image to Docker Hub
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ../
          file: ./build/VMCS.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vmcs-backend:latest